# Default values for sapien_ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
allocatePublicIPAddress: true
image: collinshillary/my-public-repo:ingress-custom-v6

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

